name: "Aqusec Trivy Scan"
on:
  push:
    branches:
      - main
jobs:
  Image-list-fetch:
    runs-on: ubuntu-latest
    outputs:
      image_list: ${{ steps.run_script.outputs.image_list }}
    steps:
      - name: Checkout code
        id: check_code
        uses: actions/checkout@v2
      - name: Fetch docker image from manifest file
        id: run_script
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
          ./kustomize build ${{ github.workspace }}/kustomize_template/1.8.2 > manifest.yaml
          IMAGE_DATA=$(python3 ${{ github.workspace }}/scripts/fetch_images.py)
          echo image_list=$IMAGE_DATA >> $GITHUB_OUTPUT
  Trivy-Scan:
    runs-on: ubuntu-latest
    needs: Image-list-fetch
    strategy:
      matrix:
        image: ${{ fromJSON(needs.Image-list-fetch.outputs.image_list) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Trivy vulnerability scanner in docker mode
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ matrix.image }}
          format: 'table'
          timeout: '30m'
        env:
          AQUA_KEY: ${{ secrets.AQUA_KEY }}
          AQUA_SECRET: ${{ secrets.AQUA_SECRET }}
          TRIVY_RUN_AS_PLUGIN: 'aqua'
          GITHUB_TOKEN: ${{ github.token }}
