name: "Code Scanning"
on:
  push:
    branches:
      - main
jobs:
  Image-list:
    runs-on: ubuntu-latest
    outputs:
      image_list: ${{ steps.run_script.outputs.image_list }}
    steps:
      - name: Checkout code
        id: check_code
        uses: actions/checkout@v2
      - name: Run script
        id: run_script
        run: |
          mkdir script_v1
          pwd
          ls -la
          ls ${{ github.workspace }}
          cd script_v1
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
          ./kustomize build ${{ github.workspace }}/kustomize_template > manifest.yaml
          python3 ${{ github.workspace }}/scripts/fetch_images.py
          python3 ${{ github.workspace }}/scripts/fetch_images.py >> $GITHUB_OUTPUT
  Trivy-Scan:
    runs-on: ubuntu-latest
    needs: Image-list
    strategy:
      matrix:
        image: ${{needs.Image-list.outputs.image_list}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Trivy vulnerability scanner in docker mode
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ matrix.image }}
          format: 'sarif'
          template: 'sarif'
          output: 'trivy-results-docker.sarif'
          severity: 'CRITICAL'
          timeout: '30m'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results-docker.sarif'
